// Generated by @adddog/monorepo-consistency
// Do not edit manually - regenerate with: pnpm generate:knip
import { defineKnipConfig } from "@adddog/monorepo-consistency";

export default defineKnipConfig({
    entry: [
        "src/vite.config.ts",
        "src/vitest.config.ts",
        "src/browser/global-setup.ts",
        "src/browser/setup-browser.ts",
    ],
    project: ["src/**/*.{ts,tsx}"],
    // WHY: all source files are unbuild entries, knip can't trace them
    ignore: [
        "src/**",
        "build.config.ts",
    ],
    // WHY: re-exported for downstream consumers, not directly used here
    ignoreDependencies: [
        "lodash-es",
        "@playwright/test",
        "@vitest/browser-playwright",
        "@vitest/ui",
        "vite",
        "vitest",
        "@types/lodash-es",
    ],
});
