// Generated by @adddog/monorepo-consistency
// Do not edit manually - regenerate with: mono knip generate
import { defineKnipConfig } from "@adddog/monorepo-consistency";

export default defineKnipConfig({
    project: ["src/**/*.{ts,tsx}"],
}, {
    ignoreDependencies: [
        "@adddog/monorepo-consistency",
        "@playwright/test",
        "@adddog/build-configs",
    ],
    project: [
        "src/**/*.{ts,tsx}",
    ],
    ignore: [
        "src/browser/global-setup.ts",
        "src/browser/setup-browser.ts",
    ],
});
